### ISSUE TITLE
delete WS JSON processing structures for the old definition.

### ISSUE THREAD

**Issue by Vanyaslav** [specure/ont-ios-client#1]
The framework covers the communication for two basic project types. For the project NKOM and the other ones. (including the very recent versions of the ONT(Moqos) project). After all server's implementation of the WS JSON structure unifies (hopefully some day - this is the basic precondition) to the NKOM version.(definitely better, but still might be improved) In the framework is used the configurable variable named "RMBT_VERSION_NEW" = NKOM.

**Comment by jozef2svrcek** [comment]
won't do
