### ISSUE TITLE
"pod spec lint" does not pass

### ISSUE THREAD

**Issue by Vanyaslav** [specure/ont-ios-client#4]
there is an issue during the pods validation phase which block proper Cocoa pods RMBTClient release. 

/var/folders/5b/w3c_vhmx3dl5s69j6t9wg56r0000gn/T/CocoaPods-Lint-20171024-65494-9bagzw-RMBTClient/Pods/Target Support Files/RMBTClient/RMBTClient-umbrella.h:18:9: note: in file included from /var/folders/5b/w3c_vhmx3dl5s69j6t9wg56r0000gn/T/CocoaPods-Lint-20171024-65494-9bagzw-RMBTClient/Pods/Target Support Files/RMBTClient/RMBTClient-umbrella.h:18:
#import "PingUtil.h"

**Comment by jozef2svrcek** [comment]
Comment from the developer: just fix error if it happened locally, and we will submit latest code to dependency repository in the future if we need it
